### ISSUE TITLE
Ecran de démarrage

### ISSUE THREAD

**Issue by smtr11** [oblique-strategies/oblique-strategies.github.io#1]
Cette tâche comprend:

- Conception de l'écran de démarrage du site.
- Maquette visuelle – pour les différents formats d'écran, voir issue #8 
- Conception du code.

**Comment by ms-studio** [comment]
Un choix de couleur a été fait semble-t-il. Peut-on avoir une référence, une charte visuelle, les codes #hexadécimaux des couleurs?

**Comment by ms-studio** [comment]
Une première version de l'écran de démarrage est active sur le site https://oblique-strategies.github.io/

Le déplacement hors-champ de l'écran est défini dans [javascript.js](https://github.com/oblique-strategies/oblique-strategies.github.io/blob/master/javascript/javascript.js).

## Comment ça marche?

Avec une combinaison de JavaScript et d'animations CSS.

Voilà ce qui se passe au clic sur le bouton:

Premièrement, ce code rend le bouton "sensible au clic":

```javascript
// 1) on identifie le bouton, par son identifiant "start", pour pouvoir le manipuler.
var startButton = document.getElementById('start');
// 2) on lui ajoute un "EventListener", il va ainsi réagir à l'événement "clic" en exécutant la fonction "premiereCarte".
startButton.addEventListener('click', premiereCarte, false);
```

Le code qui suit est inclus dans la fonction `premiereCarte()`.

En javascript, on rend transparent l'animation en ajoutant la classe CSS "transparent":

```
myCanvas.className += " transparent";
```

La transparence est définie dans le CSS, fichier [style.css](https://github.com/oblique-strategies/oblique-strategies.github.io/blob/master/css/style.css):

```css
.transparent {
  opacity : 0;
}
```

En plus de cela, afin d'avoir une transition en douceur, on a défini une transition CSS:

```css
#myCanvas {
  transition: opacity 1s ease-in-out;
}
```

Cela signifie que toute modification de la propriété "opacity" de cet élément sera appliquée avec une transition dont la durée est de 1s (une seconde).

Une fois la transparence appliquée, on va déplacer la page d'accueil _hors-champ_, et on fait apparaître le contenu du site.

```javascript
intro.style.left = "100vw"; // Fait disparaître l'animation
frame.style.right = "0vw"; // Fait apparaître le contenu
```

## Explicatifs

### Donner des noms à nos éléments, pour les manipuler en JavaScript

- "intro" est le nom de l'élément-bloc qui contient l'animation d'introduction "frame" est le nom de l'élément qui contient le reste (menu, image, texte de la carte).
- On a attribué ces noms en notant leur "id" dans le code HTML, comme dans cet exemple:

```html
<header id="intro">
  <canvas id="myCanvas" resize></canvas>
  <a id="start" class="button" href="carte.html">Stratagèmes obliques</a>
</header>
```

Pour que le Javascript puisse agir sur ces éléments, il faut les "définir". Voici la manière utilisée:

```javascript
 var myCanvas = document.getElementById('myCanvas');
 var intro    = document.getElementById('intro');
 var frame    = document.getElementById('frame');
```

Une fois qu'on les a définis, on peut s'amuser à les manipuler, déplacer, masquer... Soit en leur donnant des classes CSS, soit en modifiant directement leurs propriétés CSS avec la méthode "style".

### Une unité de mesure CSS: les viewport units

- On tire profit des valeurs CSS **vw** et **vh**, les "viewport units". Ce sont des valeurs relatives, correspondant _aux dimensions de l'écran_. **vw** signifie "viewport width", donc la largeur de l'écran. **vh** est "viewport height", donc la hauteur. Ces valeurs sont établies sur une échelle de 100. **1vw** équivaut à 1/100e de la largeur de l'écran, **50vw** à la moitié de la largeur, etc.
- Avec `intro.style.left = "100vw";` on définit la valeur CSS "left", donc l'espace à gauche de l'élément "intro". On lui donne la valeur 100vw, càd 100% de la largeur de l'écran. Cela consiste effectivement à pousser cet élément hors champ.
- On utilise également une transition CSS pour que ce déplacement se fasse en douceur.

Et voici comment on fait apparaître le contenu principal:

- Pour l'élément "frame", la valeur "right" est définie initialement, dans le _style.css_, à 100vw.

```css
#frame {
  position: absolute;
  height: 100vh;
  width: 100%;
  top: 0;
  right: 100vw;
  transition: right 1s ease-in-out;
}
```

- Cet objet "frame" est donc initialement hors-champ, car il a une marge à droite qui est de la largeur de l'écran (100vw). 
- Avec`frame.style.right = "0vw"`, on amène la valeur "right" à zéro: l'objet est repositionné et occupe la partie visible de l'écran.
- Etant donné qu'on a défini une transition, l'objet entre dans l'écran avec un effet de glissement.
