### ISSUE TITLE
Recherches Titre

### ISSUE THREAD

**Issue by mchora** [oblique-strategies/oblique-strategies.github.io#17]
Suite à un brainstorming en commun avec David concernant le nom de remplacement pour "oblique strategies", nous vous proposons les noms suivant: 

Anagrammes oblique strategies:  

- Algébrique
- Obliterate
- Girouette
- Oubliette
- Neo

Autres: 

- Crosswords
- Grotesque
- Eno (en référence à Brian Eno)
- Randomize
- Random
- RNDM
- RNDMZ
- Word-Jam
- Ideas At Ease
- IEA
- IA
- Mindful Cards
- Crossed Minds
- Crossing Minds
- MoonOne 

N'ayant toujours pas trouvé de naming fort et adéquat, nous vous invitons à bien vouloir proposer un/des nom(s) si les idées vous viennent. 

David, Miguel

**Comment by ms-studio** [comment]
Note: "Grotesque" est déjà utilisé dans ce projet dérivé des Oblique Strategies:

https://www.grotesquetablesii.com/

**Comment by tdolk** [comment]
Tri dans les titres afin d'en garder les meilleurs, suivi d'un vote en classe pour élire le meilleur.

Random Advice

Crossed Minds
Crossed Advice

Casual Minds

**Comment by tdolk** [comment]
Après un vote, **Crossed Minds** est retenu.
