### ISSUE TITLE
Page ABOUT

### ISSUE THREAD

**Issue by smtr11** [oblique-strategies/oblique-strategies.github.io#2]
Rédaction de la page ABOUT.

- Explicatif sur le projet.
- Crédits.
- Information de contact.

![tache-page-about](https://user-images.githubusercontent.com/241637/39702137-128802be-5204-11e8-84e2-0f1b7b37f064.jpg)

**Comment by ms-studio** [comment]
Pour rédiger le texte, utiliser simplement un fichier dans ce projet Github:

https://github.com/oblique-strategies/oblique-strategies.github.io/blob/master/txt/about.md

**Comment by ms-studio** [comment]
Une page "About" préparée hier par @liotse et @smtr11 : 

https://mailchi.mp/6294a988dd51/stratagemes-obliques

Que pensez-vous, si on mettait ce contenu directement dans le site, sur la page About ? Qui s'afficherait quand on clique sur Infos?
