### ISSUE TITLE
Uniformiser les fontes - système typographique

### ISSUE THREAD

**Issue by smtr11** [oblique-strategies/oblique-strategies.github.io#3]
Cette tâche comprend:

- Choix de fonte(s) typographique(s).
- Etablir un système typographique (hiérarchie), qui s'appliquera pour les cartes, le menu, les pages annexes comme #2 (page About) ou #7 (page Help).
- Définir les tailles typographiques pour qu'elles puissent être modifiées selon les tailles d'écran - voir #8 (responsive).

**Comment by smtr11** [comment]
Typographie choisi: SangBleu Sunrise / SangBleu Empire
Sunrise Livre: 

- corps de texte

- phrase des cartes

Empire Bold:

- Page d'accueil

- Navigation

- Titres

**Comment by ms-studio** [comment]
@mdutschler Une image pour visualiser?
