### ISSUE TITLE
Time out!

### ISSUE THREAD

**Issue by smtr11** [oblique-strategies/oblique-strategies.github.io#6]
Si on utilise le jeu de cartes physique, la règle implicite est que la carte tirée doit être suivie, et ne peut pas être simplement remplacée par la carte suivante.

Pour l'utilisation du site, on peut imaginer une règle similaire:

- Un certain laps de temps doit s'écouler avant de pouvoir tirer une nouvelle carte...
- Effet visuel permettant de ressentir l'écoulement de ce temps?

**Comment by tdolk** [comment]
Le délai d'attente sera exponentielle.

Carte 1
Temps d'attente supplémentaire: 0 minute
Temps total : 0 minute

Carte 2
Temps d'attente supplémentaire: 15 minutes
Temps total : 15 minutes

Carte 3
Temps d'attente supplémentaire: 30 minutes
Temps total : 45 minutes

Carte 4
Temps d'attente supplémentaire: 1 heure
Temps total : 1h 45min

Carte 5
Temps d'attente supplémentaire: 2 heures
Temps total : 3h 45min

Carte 6
Temps d'attente supplémentaire: 4 heures
Temps total : 7h 45min

Carte 7
Temps d'attente supplémentaire: 8 heures
Temps total : 15h 45min

Il n'y a pas plus de carte à tirer. Chaque jour, à 8h du matin, cela sera réinitialisé et ainsi, l'utilisateur pourra recommencer en tirant une carte sans attente.

**Comment by ms-studio** [comment]
Pour la programmation du "timeout", on pourra se baser sur un précédent projet:

https://github.com/eracom-gr451/projet-canvas-launcher

Le code JS gérant l'historique de l'utilisateur est dans ce fichier:

https://github.com/eracom-gr451/projet-canvas-launcher/blob/master/random.html

**Comment by ms-studio** [comment]
Idée : une fois le timeout implémenté, il serait utile d'avoir accès à une variante qui contourne le timeout ... par exemple pour faire une démonstration du projet, en mode exposition, etc.

Cela pourrait être fait par une variable dans l'URL.

Quelques pistes:

https://css-tricks.com/snippets/javascript/get-url-variables/

**Comment by ms-studio** [comment]
Réflexion, une méthode possible:

Enregistrer deux valeurs en cookie:
- NombreCartes: 1, 2, etc. (nombre de cartes tirées)
- DernierTirage: timestamp du dernier tirage


Au clic sur “nouvelle carte”

- test des valeurs du cookie
- en fonction du NombreCartes, on a un délai (15min, etc, voir ci-dessus)
- tester le temps actuel
- comparer avec le timestamp

- si la différence est plus grande que le delai = nouvelle carte
- sinon = message d’attente

**Comment by ms-studio** [comment]
Inspiration pour le texte du message d'attente:

<img width="978" alt="ecran-attente" src="https://user-images.githubusercontent.com/241637/40968647-5a5872a4-68b6-11e8-9e60-7402ea46d5b1.png">

**Comment by ms-studio** [comment]
@dehrensperger merci de faire un commit avec tous les changements de ce matin. Toute la partie des Cookies manque...

Il y a des chances que notre code fonctionnera une fois que le JavaScript sera chargé depuis Github.. il est vraisemblable que les cookies ne sont pas actifs quand on ouvre le site en local, comme on l'a fait ce matin.

**Comment by ms-studio** [comment]
Après un petit test: oui, c'est bien ce qui nous a bloqué ce matin!

Dans Chrome, l'écriture et lecture des cookies n'est pas possible quand on ouvre une page html en local (chemin file:///...). Les cookies ne fonctionnent que si la page est chargée en http://.

Dans certains navigateurs cela fonctionne, notamment FireFox.

Quelques informations dans StackOverflow à ce sujet: https://stackoverflow.com/questions/6232331/setting-cookies-using-javascript-in-a-local-html-file
